producer-name = produceracc1
producer-name = bp1
producer-name = bp2
producer-name = bp3
producer-name = bp4
producer-name = bp5
producer-name = bp11
producer-name = bp12
producer-name = bp13
producer-name = bp14
producer-name = bp15
producer-name = bp21
producer-name = bp22
producer-name = bp23
producer-name = bp24
producer-name = bp25
producer-name = bp31
producer-name = bp32
producer-name = bp33
producer-name = bp34
producer-name = bp35
producer-name = bp41
producer-name = bp42
producer-name = bp43
producer-name = bp44
producer-name = bp45
producer-name = bp51
producer-name = bp52
producer-name = bp53
producer-name = bp54
producer-name = bp55
producer-name = bp111
producer-name = bp112
producer-name = bp113
producer-name = bp114
producer-name = bp115
producer-name = bp121
producer-name = bp122
producer-name = bp123
producer-name = bp124
producer-name = bp125
producer-name = bp131
producer-name = bp132
producer-name = bp133
producer-name = bp134
producer-name = bp135
producer-name = bp141
producer-name = bp142
producer-name = bp143
producer-name = bp144
producer-name = bp145
producer-name = bp151
producer-name = bp152
producer-name = bp153
producer-name = bp154
producer-name = bp155


signature-provider = EOS5GnobZ231eekYUJHGTcmy2qve1K23r5jSFQbMfwWTtPB7mFZ1L=KEY:5Jr65kdYmn33C3UabzhmWDm2PuqbRfPuDStts3ZFNSBLM7TqaiL

http-server-address = 0.0.0.0:8891
p2p-listen-endpoint = 0.0.0.0:9891

wasm-runtime = eos-vm
eos-vm-oc-enable = true

#chain-state-db-size-mb = 65536
contracts-console = true
access-control-allow-origin = *
access-control-allow-headers = *
verbose-http-errors = true
http-validate-host = false
abi-serializer-max-time-ms = 100
http-max-response-time-ms = 50

# PLUGINS
plugin = eosio::chain_plugin
plugin = eosio::net_plugin
plugin = eosio::producer_plugin
plugin = eosio::producer_api_plugin

# rpc
# p2p-peer-address = 127.0.0.1:9876

# eosio
# p2p-peer-address = 127.0.0.1:9890

# prod-2
# p2p-peer-address = 127.0.0.1:9892
