producer-name = produceracc1
producer-name = bp1
producer-name = bp2
producer-name = bp3
producer-name = bp4
producer-name = bp5
producer-name = bp6
producer-name = bp7
producer-name = bp8
producer-name = bp9
producer-name = bp10
producer-name = bp11
producer-name = bp12
producer-name = bp13
producer-name = bp14
producer-name = bp15
producer-name = bp16
producer-name = bp17
producer-name = bp18
producer-name = bp19
producer-name = bp20
producer-name = bp21
producer-name = bp22
producer-name = bp23
producer-name = bp24
producer-name = bp25
producer-name = bp26
producer-name = bp27
producer-name = bp28
producer-name = bp29
producer-name = bp30
producer-name = bp31
producer-name = bp32
producer-name = bp33
producer-name = bp34
producer-name = bp35
producer-name = bp36
producer-name = bp37
producer-name = bp38
producer-name = bp39
producer-name = bp40
producer-name = bp41
producer-name = bp42
producer-name = bp43
producer-name = bp44
producer-name = bp45
producer-name = bp46
producer-name = bp47
producer-name = bp48
producer-name = bp49
producer-name = bp50
producer-name = bp51
producer-name = bp52
producer-name = bp53
producer-name = bp54
producer-name = bp55
producer-name = bp56
producer-name = bp57
producer-name = bp58
producer-name = bp59
producer-name = bp60

signature-provider = EOS5GnobZ231eekYUJHGTcmy2qve1K23r5jSFQbMfwWTtPB7mFZ1L=KEY:5Jr65kdYmn33C3UabzhmWDm2PuqbRfPuDStts3ZFNSBLM7TqaiL

http-server-address = 0.0.0.0:8891
p2p-listen-endpoint = 0.0.0.0:9891

wasm-runtime = eos-vm
eos-vm-oc-enable = true

#chain-state-db-size-mb = 65536
contracts-console = true
access-control-allow-origin = *
access-control-allow-headers = *
verbose-http-errors = true
http-validate-host = false
abi-serializer-max-time-ms = 100
http-max-response-time-ms = 50

# PLUGINS
plugin = eosio::chain_plugin
plugin = eosio::net_plugin
plugin = eosio::producer_plugin
plugin = eosio::producer_api_plugin

# rpc
# p2p-peer-address = 127.0.0.1:9876

# eosio
# p2p-peer-address = 127.0.0.1:9890

# prod-2
# p2p-peer-address = 127.0.0.1:9892
